name: Action

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: ["Container Build"]
        tag: ["Container Tag"]
    steps:
    - uses: actions/checkout@v4
    - name: Docker Build
      run: docker build -t alpine .