name: Action

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: ["Container Build"]
        tag: ["Container Tag"]
    steps:
    - uses: actions/checkout@v4
    - name: Docker Build
      if: matrix.build == 'Container Build'
      run: docker build -t alpine .
    - name: Docker Tag
      if: matrix.tag == 'Container Tag'
      run: docker tag alpine:latest alpine:1.0