name: Action

on:
  push:
  workflow_dispatch:
env:
  FRONTEND: "frontend"
  BACKEND: "backend"
  TERMINAL: "terminal"

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Build ${{ env.FRONTEND }}}
      run: docker build -t frontend:latest frontend/
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Build ${{ env.BACKEND }}
      run: docker build -t backend:latest backend/

    # - name: Docker Build ${{ env.TERMINAL }}
    #   run: docker build -t terminal:latest terminal/
  scan-frontend:
    name: Frontend Container Scan
    runs-on: ubuntu-latest
    needs: [build-frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Vision One Container Security Scan - Frontend
        run: |
          docker build -t frontend:latest frontend/
          chmod +x tmas_install.sh && ./tmas_install.sh
          export TMAS_API_KEY=${{ secrets.TMAS_API_KEY }}
          docker save frontend:latest > image.tar
          tmas scan docker-archive:image.tar --malwareScan
  scan-backend:
    name: Backend Container Scan
    runs-on: ubuntu-latest
    needs: [build-backend]
    steps:
      - uses: actions/checkout@v4
      - name: Vision One Container Security Scan - Backend
        run: |
          docker build -t backend:latest backend/
          chmod +x tmas_install.sh && ./tmas_install.sh
          export TMAS_API_KEY=${{ secrets.TMAS_API_KEY }}
          docker save backend:latest > image.tar
          tmas scan docker-archive:image.tar --malwareScan