name: Action

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Build
      run: docker build -t alpine:v1 .
  tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Docker Tag
      run: docker tag alpine:v1 ghcr.io/felipecosta09/alpine:v1